version: "3.9"

services:
  magic-kingdom-accounting:
    image: magic-kingdom-accounting:latest
    restart: always
    environment:
      AWS_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
    ports:
      - "8080:8080"
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8001:8000"